alias: Woonkamer lamp master uit
trigger:
- device_id: e04cb9d11eda4d62a6ff43cf327f5d85
  domain: light
  entity_id: light.woonkamer_spots
  platform: device
  type: turned_off
condition: []
action:
- service: switch.turn_off
  entity_id: switch.vloerlamp
- service: switch.turn_off
  entity_id: switch.garderobe
- service: light.turn_off
  entity_id: light.eettafel_light  