
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/

wifi_ssid: Pjotr24
wifi_pw: rapidteapot022
esphome_api_password: Thofk25!
esphome_ota_password: p3#4xQ_